version: 1.0.0
name: web
description: Web commands
commands:
  - name: commmit
    command: boilerplate
  - name: test
    command: test
    args:
      - name: --teste
        description: Teste argument

    